import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Hand-written rather than autogenerated. Every page here is committed, and the
 * order is an argument -- install, then configure, then the reference material
 * -- which an autogenerated tree would flatten into alphabetical order.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['installation', 'usage', 'migration'],
    },
    {
      type: 'category',
      label: 'Design System',
      link: {type: 'doc', id: 'design-system/index'},
      items: ['design-system/tokens', 'design-system/typography'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/exports',
        'reference/components',
        'reference/assets',
        'reference/customization',
      ],
    },
    'contributing',
  ],
};

export default sidebars;
